language: node_js

node_js:
  - "9"
  - "8"
  - "7"
  - "6"

after_success: '[[ "$TRAVIS_NODE_VERSION" == "9" ]] && ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
